---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: azure-remount
  namespace: default
  labels:
    app: azure-remount
spec:
  selector:
    matchLabels:
      app: azure-remount
  template:
    metadata:
      labels:
        app: azure-remount
    spec:
      hostIPC: true
      hostNetwork: true
      hostPID: true
      containers:
        - image: "wzrdtales/cockroachdb-azure:remount"
          imagePullPolicy: "Always"
          name: azure-remount
          securityContext:
            privileged: true
          volumeMounts:
            - name: home
              mountPath: /home
            - name: mnt
              mountPath: /mnt
            - name: dev
              mountPath: /dev
            - name: sys
              mountPath: /sys
            - name: hkeys
              mountPath: /root/hkeys
      volumes:
        - name: home
          hostPath:
            path: /home
        - name: mnt
          hostPath:
            path: /mnt
        - name: dev
          hostPath:
            path: /dev
        - name: sys
          hostPath:
            path: /sys
        - name: hkeys
          hostPath:
            path: /root/.ssh
